spring.application.name=tpops
spring.config.import=optional:file:../.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.hbm2ddl.auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=${SERVER_PORT:8080}

spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE:10MB}

logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.level.com.shinhan.tpops=${LOGGING_LEVEL_APP:INFO}
logging.file.name=${LOGGING_FILE_NAME:}

tpops.elasticsearch.endpoint=${TPOPS_ELASTICSEARCH_ENDPOINT:}
tpops.elasticsearch.api-key=${TPOPS_ELASTICSEARCH_API_KEY:}
tpops.elasticsearch.ca-cert-path=${TPOPS_ELASTICSEARCH_CA_CERT_PATH:}
tpops.elasticsearch.index-name=${TPOPS_ELASTICSEARCH_INDEX_NAME:tp-svclog-test}
tpops.elasticsearch.timestamp-field=${TPOPS_ELASTICSEARCH_TIMESTAMP_FIELD:@timestamp}
tpops.elasticsearch.service-name-field=${TPOPS_ELASTICSEARCH_SERVICE_NAME_FIELD:tp_svc_id}
tpops.elasticsearch.response-time-field=${TPOPS_ELASTICSEARCH_RESPONSE_TIME_FIELD:tp_resp_time}
tpops.elasticsearch.service-bucket-size=${TPOPS_ELASTICSEARCH_SERVICE_BUCKET_SIZE:10000}
